config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :beekeepers
  root "welcome#index"
  get "/apiary" => "apiary#index", :as => :apiary

  get "/workers/new/:worker_guid" => "workers#new", :as => :new_worker
end

app/models/apiary.rb
class Apiary < ActiveRecord::Base
  belongs_to :beekeeper
  has_one :apiary, :class => Apiary
  has_many :workers
end

app/models/beekeeper.rb
class Beekeeper < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :confirmable, :lockable,
          :recoverable, :rememberable, :trackable, :validatable
  has_one :apiary
  has_many :hive_beekeepers, :class_name => "HiveBeekeepers"
  has_many :hives, :through => :hive_beekeepers

  def is_admin?
    self.role == 'admin'
  end
end

app/models/concerns/has_access_token.rb
module HasAccessToken
  extend ActiveSupport::Concern

  included do
    before_create :generate_access_token
  end

  protected

  def generate_access_token
    self.access_token = SecureRandom.hex(32)
  end
end

app/models/concerns/has_guid.rb
module HasGuid
  extend ActiveSupport::Concern

  included do
    before_create :generate_guid
  end

  protected

  def generate_guid
    self.guid = SecureRandom.uuid if self.guid.blank?
  end
end

app/models/hive.rb
class Hive < ActiveRecord::Base
  has_many :workers
  belongs_to :apiary
  has_many :hive_beekeepers, :class_name => "HiveBeekeepers"
  has_many :beekeepers, :through => :hive_beekeepers
end

app/models/hive_beekeepers.rb
class HiveBeekeepers < ActiveRecord::Base
  belongs_to :hive
  belongs_to :beekeeper
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  include HasGuid
  include HasAccessToken

  belongs_to :hive
  belongs_to :apiary
end

app/controllers/apiary_controller.rb
class ApiaryController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_beekeeper!

  protected

  def authenticate_admin_beekeeper!
    requires_admin!
  end

  def  requires_admin!
    current_beekeeper && current_beekeeper.is_admin?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_beekeeper!
  def index
    if (current_beekeeper)
      redirect_to apiary_path
    end
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  skip_before_filter :authenticate_beekeeper!, :only => [:new]

  def new
    @worker = Worker.new(:guid => params[:worker_guid])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apiary/index.html.haml
.jumbotron
  Logged in and rocking it!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HivewingWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img alt="Brand" src="http://placehold.it/25x25/ffb600&text=HW">
      </a>
    </div>
    <p class="login-info navbar-text ">
      <% if beekeeper_signed_in? %>
        Logged in as <strong><%= current_beekeeper.email %></strong>.
        <%= link_to 'Edit profile', edit_beekeeper_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_beekeeper_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_beekeeper_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_beekeeper_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
  </div>
</nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.haml
%h1 HiveWing.io
%p
  A really cool app for all your workers.
%h3 Coming Soon!

app/views/workers/new.html.haml
%h1 New Worker

%p
  This is going to set up worker
  =@worker.guid